import { Mulish } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const mulish = Mulish({
  variable: "--font-mulish",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${mulish.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
